# Generated by Django 3.1 on 2020-08-07 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diary',
            name='photoObjects',
        ),
        migrations.AddField(
            model_name='diary',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='photoobject',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='photoobject',
            name='diary',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='diary', to='diary.diary'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=30)),
                ('date', models.DateTimeField(auto_now=True)),
                ('text', models.TextField(default='')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diary.photoobject')),
            ],
        ),
    ]
